### ISSUE TITLE
Multiple specific paymentmethods

### ISSUE THREAD

**Issue by sjorritsma** [Viincenttt/MollieApi#164]
Is there a way to add 2 or more specific Paymentmethods to the paymentrequest??

The code I have : Method = PaymentMethod.Belfius

I want only for the belgium customers the choice between Belfius and Bancontact.

What I tried JSON Serialize, Array and list. In the documentation of Mollie the method can be a array.

**Comment by beko1997** [comment]
Currently this does not seem to be supported by this library. It is possible to get a list of payment methods though. So you might be able to display a list to the customer by getting a list of payment methods, filtering down to the payment methods you want to display (and are supported for the amount due) and display the payment methods accordingly.

It could be a nice addition to support providing multiple payment methods but in order to prevent breaking changes it should be added as an extra property.

**Comment by sjorritsma** [comment]
Thanks  Bert for your comment. As a workaround I added a website profile in Mollie with the paymentmethods.

**Comment by Viincenttt** [comment]
Would be a nice feature to add! I'll add the help-wanted tag

**Comment by Viincenttt** [comment]
This feature is now supported in version 2.1.0.0. Take a look at the release notes for a full list of fixes and changes:
https://github.com/Viincenttt/MollieApi/releases/tag/2.1.0.0
