### ISSUE TITLE
TokenResponse always has null values

### ISSUE THREAD

**Issue by whats-it-nl** [Viincenttt/MollieApi#188]
Hi,

We're implementing OAuth to use the API.
When we use:
ConnectClient connectClient = new ConnectClient(ClientID, ClientSecret);
TokenRequest request = new TokenRequest(code, redirecturl);
TokenResponse response = await connectClient.GetAccessTokenAsync(request);
All the values, except for 'ExpiresIn', are null.

Am I missing something?

Kind regards,
Casper

**Comment by Viincenttt** [comment]
Hi,

Perhaps there is an error in the background. I've recently been rewriting the `ConnectClient` and also found a few issues with it. I am planning to release a new version of the API client later this week. Maybe you can take a look if this branch fixes the issue you have: https://github.com/Viincenttt/MollieApi/tree/2.1.0.0

If not, I'll take a more in-depth look. 

Kind regards,
Vincent

**Comment by whats-it-nl** [comment]
Hi,

Found the bug.
In the connectclient.cs line 54 is:
httpRequest.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
and should be:
httpRequest.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/x-www-form-urlencoded"));

Kind regards,
Casper

**Comment by Viincenttt** [comment]
I've looked into a bit, because the API should return JSON. It turns out that the `TokenResponse` class was missing the `JsonProperty` attributes, which is why some of the values were `null`. This is fixed in the 2.1.0 branch during the following commit:
https://github.com/Viincenttt/MollieApi/commit/2d7f377a7c905788f78c0097462e150bfa998623

The release of this branch will probably be done today or tomorrow. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This issue is now fixed in version 2.1.0.0. Take a look at the release notes for a full list of fixes and changes:
https://github.com/Viincenttt/MollieApi/releases/tag/2.1.0.0
