### ISSUE TITLE
Error on Domestic

### ISSUE THREAD

**Issue by Fit2Page** [Viincenttt/MollieApi#191]
Hi,

After years of more or less flawless functioning today I get the following error: Bericht: Error converting value "domestic" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFeeRegion]'. Path 'details.feeRegion'

This is happening with a customer who tries to pay with CC.
Do you think something has changed in th Mollie API?

Marc

**Comment by rworonk15** [comment]
Hey, 

I had almost the same problem. 
The user that did the payment used CC, more specific a 'MoonCard'.

![Capture d’écran 2020-10-12 à 17 27 35](https://user-images.githubusercontent.com/19306947/96129457-f16b0b00-0ef6-11eb-8e43-616249dc464a.png)

**Comment by Viincenttt** [comment]
Hi,

This issue should be fixed if you upgrade to the latest version. I have converted all enums to string values because Mollie is continiously adding values to these types of lists. 

Take a look at the CreditCardFeeRegion class in the current version. It's now just a list of constant strings instead of enum values:
https://github.com/Viincenttt/MollieApi/blob/6d6384317ff15e40afe78e02a23d323b37678308/Mollie.Api/Models/Payment/Response/Specific/CreditCardPaymentResponse.cs#L93

**Comment by Viincenttt** [comment]
Closing this for now. Let me know if you are still having issues and are using the latest version of the library.

**Comment by Fit2Page** [comment]
Hi,

 

After migrating from 2.0.7 to 2.1.0 I get the following error:

 

Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

Can you help?

 

Met vriendelijke groet,

Marc Waanders

 

https://www.fit2page.nl/F2P-logo.png

 

FIT2PAGE

De Greune 1a

7483 PH Haaksbergen

 

Web: www.fit2page.nl <https://www.fit2page.nl/> 

E-mail: info@fit2page.nl

 

Tel.: 053-5729494

**Comment by Fit2Page** [comment]
Hi,

Solved this by adding:

Install-Package System.Diagnostics.DiagnosticSource -Version 4.7.1
