### ISSUE TITLE
Unprocessable Entity - The payment method is invalid

### ISSUE THREAD

**Issue by flo-rider** [Viincenttt/MollieApi#219]
I downloaded and built the latest version. When trying to initiate a Bancontact payment request like so:
	
    Mollie.Api.Models.Payment.Request.PaymentRequest paymentRequest = new Mollie.Api.Models.Payment.Request.PaymentRequest();
    paymentRequest.Method = PaymentMethod.Bancontact;
    paymentRequest.Amount = new Amount(mollieCurrency, priceInclTaxAndTransactionCostsDotDecimal);
    paymentRequest.Description = paymentDescription;
    paymentRequest.RedirectUrl = paymentRedirectUrl;
    var paymentResponse = await paymentClient.CreatePaymentAsync(paymentRequest);

I then get the error:

> Unprocessable Entity - The payment method is invalid

On line `var paymentResponse = await paymentClient.CreatePaymentAsync(paymentRequest);`	

Why?

**Comment by Viincenttt** [comment]
Hi @flo-rider ,

Can you check if the Bancontact payment method is activated on your Mollie dashboard?

Kind regards,
Vincent

**Comment by flo-rider** [comment]
Hi @Viincenttt , thanks for your prompt reply. Yes, the Bancontact payment method is enabled on my Mollie account. What else could it be?

**Comment by flo-rider** [comment]
HI @Viincenttt , sorry to contact you again but any other ideas what this could be?

**Comment by Viincenttt** [comment]
Hi @flo-rider ,

I am not sure. I'm not able to reproduce the problem. I've tried the following code and the payment is created without any problems.
```
PaymentRequest paymentRequest = new PaymentRequest() {
                Amount = new Amount(Currency.EUR, "100.00"),
                Description = "Description",
                RedirectUrl = this.DefaultRedirectUrl,
                Method = PaymentMethod.Bancontact
            };

            PaymentResponse result = await this._paymentClient.CreatePaymentAsync(paymentRequest);
```

Are you using the latest version of the library?

Kind regards,
Vincent

**Comment by flo-rider** [comment]
Hi @Viincenttt 

Thanks for getting back to me.

I'm using library version 2.1.0.4

I translated the actual code I used to C# as more folks use that, however, I'm actually working on a legacy project that uses VB.NET. Here's the production code:


		Dim paymentRequest As New Mollie.Api.Models.Payment.Request.PaymentRequest
		paymentRequest.Method = PaymentMethod.Bancontact
		paymentRequest.Amount = New Amount(mollieCurrency, priceInclTaxAndTransactionCostsDotDecimal)
		paymentRequest.Description = paymentDescription
		paymentRequest.RedirectUrl = paymentRedirectUrl
		Dim paymentResponse As PaymentResponse = Await paymentClient.CreatePaymentAsync(paymentRequest)

I think functionally it does the exact same as the code you shared.
The error is thrown on this line: `Dim paymentResponse As PaymentResponse = Await paymentClient.CreatePaymentAsync(paymentRequest)`

It happens for all payment methods (Bancontact, Giropay) where the type is `Mollie.Api.Models.Payment.Request.PaymentRequest` instead of an explicit type, e.g. `Dim paymentRequest As New Mollie.Api.Models.Payment.Request.PayPalPaymentRequest`

**Comment by Viincenttt** [comment]
Hi @flo-rider ,

I still don't know what could be wrong. I haven't tried it in VB, but the results should be the same. Can you try setting the `Method` property to a string value, like so:
```
paymentRequest.Method = "Bancontact"
```

If it still doesn't work, we can try to analyse the actual JSON that is sent to Mollie. We can do this by setting a breakpoint in the `SendHttpRequest` method of the `BaseMollieCient`. This should give us more insight in what is causing this issue.

**Comment by flo-rider** [comment]
Hi @Viincenttt 

Yes, I had already tried setting a hard string value, but the same error occurred.
I also tried Fiddler to analyze traffic but did not find any JSON payload.
I now tried debugging and see what was sent over, but am unsure which variable I should inspect and share? See screenshot below.
Thanks again!
![mollie](https://user-images.githubusercontent.com/7127039/108497460-c2e9ac00-72ab-11eb-9883-fcac2ad82582.png)

**Comment by Viincenttt** [comment]
Hi @flo-rider ,

In order to investigate this issue, you'll have to download the sources of the library and add the project to your solution instead of downloading the NuGet package. Alternatively, you should be able to step into the actual library code, since the .pdb (debugging files) are included in the NuGet package. 

After that, you should set a breakpoint and inspect the `jsonData` variable in this file: 
https://github.com/Viincenttt/MollieApi/blob/518e181db42868b34c59a5c935b44a648f8b3b16/Mollie.Api/Client/BaseMollieClient.cs#L40

Currently there isn't really an easier way to do this unfortunately. If I find some time in the future, I'll try to add some logging + settings to analyse requests and responses a little bit easier. 

Kind regards,
Vincent

**Comment by flo-rider** [comment]
Hi @Viincenttt <

Thanks again. I added your source as 2nd project in my solution. Here's the value of jsonData (anonymized my domainname) when trying a Bancontact payment:

"{\"amount\":{\"currency\":\"EUR\",\"value\":\"100.00\"},\"description\":\"Test notifications\",\"redirectUrl\":\"https://www.example.com/paymentvalidate?oid=89&transactiontype=subscription&lang=nl\",\"method\":[\"4\"]}"

**Comment by Viincenttt** [comment]
To be honest I am very confused. Instead of passing "Bancontact" to the payment method, it seems to add "4". That doesn't really make any sense to me! In the past the PaymentMethod class was actually an enum instead of a list of constant strings. Is it possible that PaymentMethod.Bancontact actually references the old enum? This would only be possible if you are using two conflicting versions of the library and are referencing the old one in the code where you are creating the payment. If that doesn't work, I really don't have any idea why it is passing in "4" instead of "Bancontact". 

Would you be able to create a small VB.NET example project that demonstrates the problem that you could send to me? I'd be happy to give it a try and figure this out. You send create the project on your own GitHub or add me on LinkedIn and send it to me: https://www.linkedin.com/in/vincent-kok-4aa44211/

Kind regards,
Vincent

**Comment by flo-rider** [comment]
Found it! I had my own enum type `PaymentMethod` that was conflicting with the one in Mollie.Api. Now it works! Thanks for your help!

**Comment by Viincenttt** [comment]
Haha! Glad I could be of help. Good luck :)

Kind regards,
Vincent
