### ISSUE TITLE
ConsumerAccount is gone in MandateRequest

### ISSUE THREAD

**Issue by FlexxisDeveloper** [Viincenttt/MollieApi#233]
Since version 2.1.0.6 the property ConsumerAccount (used for the IBAN number) is gone.

I don't see any alternatives and according to the Mollie API reference it is still used.

**Comment by Viincenttt** [comment]
Hi @FlexxisDeveloper 

Take a look at this commit: https://github.com/Viincenttt/MollieApi/commit/ac8475d453a087ebe5a5b53f2b1c8883bc33665d#diff-3808b5931c74f73120135fd31c785c6ab3e16395bf7bd51050355c9614de7285

The property has been moved to a specific class, because the property isn't relevant for all Mandate Request types. Sorry, this should have been more clear in the release notes.
