### ISSUE TITLE
Settlements API

### ISSUE THREAD

**Issue by Foxxie** [Viincenttt/MollieApi#24]
@Viincenttt thank you for all the work you put into the MollieApi works great!!

But what I'm missing is the possibility to find out which payments are included in a settlement to my bank account. Now I'm looking at the Mollie API documentation and it tells me that there is the Settlements API with the function: "List settlements" which returns all information I'm looking for (transaction ID's within a settlement ID and date) but I see it isn't implemented in the C# MollieApi. Do you have any plans to implement it? I was wondering if it is difficult to implement? And where to start if I would like to look into it?

**Comment by Viincenttt** [comment]
Hi,

I am currently only supporting the Customer, Issuer, Mandate, Payment, PaymentMethod, Refund and Subscription API's. Currently I'm working on a slight overhaul of my library to make adding some of the missing API's easier. This process is almost complete, I'm hoping to finish it this weekend. I'll see if I can pitch in the Settlement API as well, since it shouldn't be much work. 

I can't promise any date, but it's coming soon! :)

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
I have actually just finished the restructuring of the library. The MollieClient is now obsolete and split over smaller classes. Each Mollie API now has it's own API client class, such as PaymentClient, PaymentMethodClient etcetera. 

I have looked into adding the Settlement API into the project, but I'm afraid I'm not able to do it myself. I only have access to a test API key at the moment, which means I am not able to retrieve any settlements. I am willing to help you out if you are planning to implement the Settlement API yourself.
