### ISSUE TITLE
Addition to #272 Missing Testmode parameter in various clients

### ISSUE THREAD

**Issue by whats-it-nl** [Viincenttt/MollieApi#274]
Small addition to #272 :

- [x] chargebacksClient.GetChargebackAsync() (missing Testmode parameter)
- [x] subscriptionRequest (profileId missing)

Will do some more testing next week on our dev environment to find if there are more parameters missing

**Comment by Viincenttt** [comment]
Hi @whats-it-nl ,

Thank you for reporting the above issues. The ChargebacksClient.GetChargebackAsync() method does not have a `testmode` parameter since this parameter is not listed in the Mollie documentation: https://docs.mollie.com/reference/v2/chargebacks-api/get-payment-chargeback. This could be a mistake on their end, as I think this method should have a testmode parameter. The `profileId` parameter also seems to be missing in this method. The `GetChargebacksListAsync` method of the `ChargebacksClient` also does not have a `testmode` parameter. For this method, the `testmode` parameter also is not listed in the Mollie documentation. 

The `SubscriptionRequest` object is indeed missing some parameters. I will add these. 

Kind regards,
Vincent

**Comment by whats-it-nl** [comment]
I see it's not in the documentation for the chargeback, I got it from an error within our environment.
Will raise this with Mollie and see what they say about it.
Within Postman it actually works when you send the testmode and profileid.
So it's probably an documentation mistake

Kind regards,
Casper

**Comment by Viincenttt** [comment]
Hi @whats-it-nl ,

Did you get any reaction from Mollie about this? If not, I can also forward it to my contact person.

Kind regards,
Vincent

**Comment by whats-it-nl** [comment]
Hi @Viincenttt,

I sent a reminder today and they have forwarded it internally.
They will come back at me when they know more.

Kind regards,
Casper

**Comment by whats-it-nl** [comment]
Hi @Viincenttt 

Unfortunately Mollie doesn't understand what I mean.
I sent them a detailed explanation with screenshots, so hopefully it will be clear now

**Comment by whats-it-nl** [comment]
Hi @Viincenttt ,

Mollie answered with the following:
----------
26 sep. 2022 11:49 CEST 


I checked with Engineering team and as you mentioned you can/need indeed just specify testmode = true if you want to get the chargebacks from test. It just doesn’t seem to have been specifically mentioned under Access token parameters in the documentation of  [Get chargeback — Chargebacks API v2 documentation — Mollie] like in GET payment

We will ask Engineering team to add it in the documentation
----------
So it should be in there soon

**Comment by Viincenttt** [comment]
Good to know! I'll add support for the testmode parameter soon.

**Comment by Viincenttt** [comment]
Hi @whats-it-nl ,

I just added a commit that adds support for the testmode parameter in all chargebacks api methods. I'm hoping to release a new version of the library somewhere this weekend.

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This is now live in version 2.1.0.15: https://github.com/Viincenttt/MollieApi/releases/tag/2.1.0.15
