### ISSUE TITLE
1.4.4. Does not compile on VS 2015 out-of-the box

### ISSUE THREAD

**Issue by marcverkade** [Viincenttt/MollieApi#35]
![image](https://user-images.githubusercontent.com/7193722/29219151-8162e79c-7eb7-11e7-9207-3f341f516c9e.png)

**Comment by Viincenttt** [comment]
Hi Marc,

This is because I recently migrated the project to use .NET standard. This also means the project now uses the new cleaned up csproj format. Unfortunatly, this format is only supported by Visual Studio 2017. 

If you still want to run this project, you can download the free community edition of Visual Studio 2017.

Kind regards,
Vincent

**Comment by marcverkade** [comment]
OK, i understand but for now I do not see the need for us to update our apps and solutions to 2017.
I merged the changes in the current project except the MollieBase stuff.
Thanx for your support!

**Comment by Viincenttt** [comment]
Hi Marc,

You don't have to include the source code into the project, just install the Nuget package instead. Much easier and it won't matter what Visual Studio version you are using. To install, open the package manager console in Visual Studio and type the following command: 
Install-Package Mollie.Api 

Kind regards,
Vincent

**Comment by marcverkade** [comment]
I know, but our policy to compile all sourcecode of the libraries we us...
It works great, thanx!

**Comment by Viincenttt** [comment]
Alright, no problem!
